camel.zero.auth.key=za_live_5423a1a54974c01fc4c865a3f250312abf01aba8f0e21b48
camel.default.page.size=15
camel.email.password=ynxq gizd vpmr ikli
camel.email.username=isabiryeelijah10@gmail.com
camel.email.host=smtp.gmail.com
camel.email.host.port=587
